apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEF6TURJeApOREEyTkRsYUZ3MDBNVEF6TURJeE5EQTJORGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEbEkyRVEzSG5lc3ZXOFQ2SUVaWWhLbVg5ZnVtNFVqRjdGNFAzNTkxc2tQVDh5UU9HTwp6OVlxNEFUb3B0ZWxiNE41aDlRQ0JwQVFFZndQblFNcHhaZDFKNmFtMlBnN0xoN09yUUg4ZWdzZE1BQkpnR2NMClVYTUV3ZFFOMWlha2VLWHc0UTBVMURuWXoyeCt2dEZRVWpiVE5nQkhWR2duUVJCTlpicjNlUGpxdEt0ZjBwMXEKY0FaU3gwWUV5VjROc2NpRTZ3OUNGVmtDZ0YzRC96WERaL0RZbml4RFJuYlRVYzNTVkYrdFpFbjM3aTJIRlNNYgo0c0JpYTJYZWxyV3Z6c2pJTmtpemJXS1JmVjQ1ZHRKKzVTT0lmOEVlNkQ5dnBtRUpqclhBSmFyRE12YXpwdkkzCkppc3RMZndJVHNCdk5Qa1ZXbGlmMG1XMXVQaklpbzNsYnpvbEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRMclNRdzQ1KzN2aHZhNkw0Mwp5ZUZXWFZxSWd6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtM0dvUFdFYlh0WTkvL1U1bG5GTDg1MEFJaytLCmRqaVVXZ0RkUS9VNFhYREdiejMwZFVNYkpLK2VmSUpPUmovVFRvNzRZZms2QW5VdHN4TnUwbnJtcGZlWERRb3kKdGJJL1ZGaThjS1MwSjNuT3N4dXR6MVczM3ZTRENvVHkvYTM1YjBNc0xQZDA2ckp1aWZNNlpYZkJnaXU1VnRycQp2aFU3QWNGSDRJOHQyQ1pUQkl3Vk9Pb2NkckJIWmJodDJyZThoWWJJQWxnS25YejIxODJIRHNoaGNRVUFnNy94ClFqTzFiUFFTenRmWjFZWHdxRUJ2NDhBdlRUMms4ZXZiRFpXMC92dGlDaTlUOGxXYzNad3pGRTRUM2d0RGJFbHoKQ2ZUa2V6eG1pcmoyazFUb2NEK3pDTUZqRDVmSE5zQnBYR25FWldMZEs1WkRMejM4WEU5Qzk5aDdMUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4a8067c7-e950-4d01-9d3e-4419dce66839.k8s.ondigitalocean.com
  name: do-lon1-march8th-kubernetes
contexts:
- context:
    cluster: do-lon1-march8th-kubernetes
    user: do-lon1-march8th-kubernetes-admin
  name: do-lon1-march8th-kubernetes
current-context: do-lon1-march8th-kubernetes
kind: Config
preferences: {}
users:
- name: do-lon1-march8th-kubernetes-admin
  user:
    token: 9a3a16de62e25b171f864edb9c1b39b71640f0ae9adeef42c4420842f8769259
